### ISSUE TITLE
Discussion of Firm

### ISSUE THREAD

**Issue by UniQP** [gablin/ghb-thesis#3]
> Braun et al. [58] introduced another graph-based IR, called F irm , but because
> it is based on the Click-Paleczny graph F irm also does not fulfill R3. Moreover, it
> fulfills neither R4 nor R8.

In my opinion Firm fulfills R3 and R8. Can you correct it or explain why this is not the case?

**Comment by gablin** [comment]
You are correct. I've revised the discussion accordingly. Thanks!
