### ISSUE TITLE
Discussion of Buchwald and Zwinkau [60]

### ISSUE THREAD

**Issue by UniQP** [gablin/ghb-thesis#4]
> In addition, since the SSA graph is devoid of control-flow information, none of the -based techniques can support inter-block instructions.

1. There's a PBQP missing in the sentence
2. We also support patterns than span multiple basic blocks (as Firm is not "devoid of control-flow information")

**Comment by UniQP** [comment]
Ah, just saw that your definition of inter-block instructions differs from what I expected.

You can close here after you have inserted the "PBQP".

**Comment by gablin** [comment]
PBQP inserted. Thanks for finding this bug!
